name: SwiftADB
options:
  bundleIdPrefix: soy.mdempsky
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"

packages:
  ADB:
    path: .

targets:
  SwiftADB:
    type: application
    platform: iOS
    sources:
      - Sources/App
    dependencies:
      - package: ADB
        product: ADB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: soy.mdempsky.SwiftADB
        INFOPLIST_FILE: Sources/App/Info.plist
        SWIFT_VERSION: 5.9
        DEVELOPMENT_TEAM: 7QU9C62CVX
        CODE_SIGN_STYLE: Automatic

  AndroidScreenshot:
    type: application
    platform: macOS
    sources:
      - Sources/ScreenshotApp
    dependencies:
      - package: ADB
        product: ADB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: soy.mdempsky.AndroidScreenshot
        INFOPLIST_FILE: Sources/ScreenshotApp/Info.plist
        SWIFT_VERSION: 5.9
        DEVELOPMENT_TEAM: 7QU9C62CVX
        CODE_SIGN_STYLE: Automatic
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: YES

schemes:
  AndroidScreenshot:
    build:
      targets:
        AndroidScreenshot: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
